import SwiftUI
import AppKit
import Foundation
import Combine
import Carbon
import ApplicationServices
import os

// MARK: - Data Model

/// `nonisolated` so its Codable conformance is callable from the persistence IO queue.
/// Without it, the project's `-default-isolation=MainActor` flag would bind the
/// conformance to the main actor and emit a Swift 6 forward-compat warning.
nonisolated struct ClipItem: Identifiable, Codable, Equatable {
    let id: UUID
    let text: String
    var date: Date
    var pinned: Bool = false
}

// MARK: - ViewModel

final class ItemsViewModel: ObservableObject {
    @Published private(set) var items: [ClipItem] = []
    private let limit = 100
    /// Per-item character cap. Beyond this, the stored text is truncated with a marker.
    /// Prevents a single very large copy (e.g., a multi-megabyte CSV) from bloating the
    /// encrypted history file and slowing every subsequent save.
    private static let maxItemChars = 100_000
    private static let truncationMarker = "\n\n[…truncated by Clip-Board]"
    private let saveSubject = PassthroughSubject<Void, Never>()
    private var cancellables: Set<AnyCancellable> = []

    init() {
        items = PersistenceManager.shared.load()

        // Debounce on main so the items read happens on the same queue that mutates it.
        // PersistenceManager.save then dispatches encode/encrypt/write to its own ioQueue.
        saveSubject
            .debounce(for: .milliseconds(300), scheduler: DispatchQueue.main)
            .sink { [weak self] in
                guard let self else { return }
                PersistenceManager.shared.save(items: self.items)
            }
            .store(in: &cancellables)
    }

    private func scheduleSave() { saveSubject.send(()) }

    /// Adds an item; preserves internal whitespace/newlines, only trims leading/trailing,
    /// and truncates beyond `maxItemChars`. Dedupes by exact equality of the stored text.
    func addItem(_ text: String) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        let stored: String
        if trimmed.count > Self.maxItemChars {
            stored = String(trimmed.prefix(Self.maxItemChars)) + Self.truncationMarker
        } else {
            stored = trimmed
        }

        if let existingIndex = items.firstIndex(where: { $0.text == stored }) {
            var existing = items.remove(at: existingIndex)
            existing.date = Date()
            items.insert(existing, at: 0)
            scheduleSave()
            return
        }

        let newItem = ClipItem(id: UUID(), text: stored, date: Date())
        items.insert(newItem, at: 0)
        trimIfNeeded()
        scheduleSave()
    }

    func togglePin(_ id: UUID) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        items[index].pinned.toggle()
        trimIfNeeded()
        scheduleSave()
    }

    func deleteItem(_ id: UUID) {
        if let idx = items.firstIndex(where: { $0.id == id }) {
            items.remove(at: idx)
            scheduleSave()
        }
    }

    func clearHistory(removePinned: Bool = false) {
        if removePinned {
            items.removeAll()
        } else {
            items.removeAll(where: { !$0.pinned })
        }
        scheduleSave()
    }

    private func trimIfNeeded() {
        let nonPinned = items.filter { !$0.pinned }
        if nonPinned.count > limit {
            let toRemove = nonPinned.dropFirst(limit)
            let idsToRemove = Set(toRemove.map { $0.id })
            items.removeAll { idsToRemove.contains($0.id) }
        }
    }
}

// MARK: - Clipboard Watcher

final class ClipboardWatcher {
    static let shared = ClipboardWatcher()
    private init() {}

    // Pasteboard markers used by password managers and similar tools.
    private static let transientTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    private var lastStoredText: String?
    private var onNewItem: ((String) -> Void)?

    deinit { timer?.invalidate() }

    func start(onNewItem: @escaping (String) -> Void) {
        self.onNewItem = onNewItem
        stop()
        lastChangeCount = -1

        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkClipboard()
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t

        DispatchQueue.main.async { [weak self] in
            self?.checkClipboard()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func checkClipboard() {
        let pb = NSPasteboard.general
        let change = pb.changeCount
        guard change != lastChangeCount else { return }
        lastChangeCount = change

        // Skip items marked transient/concealed/auto-generated by other apps.
        let types = pb.types ?? []
        if types.contains(where: { Self.transientTypes.contains($0) }) { return }

        var text: String?
        if let s = pb.string(forType: .string) {
            text = s
        } else if let objects = pb.readObjects(forClasses: [NSString.self], options: nil) as? [NSString],
                  let first = objects.first {
            text = first as String
        }

        guard let raw = text else { return }
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        guard trimmed != lastStoredText else { return }
        lastStoredText = trimmed

        onNewItem?(raw)
    }
}

// MARK: - Hotkey Manager

final class HotkeyManager {
    static let shared = HotkeyManager()
    private init() {}

    private var hotKeyRef: EventHotKeyRef?
    private var handler: (() -> Void)?
    private var eventHandlerRef: EventHandlerRef?

    static var eventSpec = EventTypeSpec(
        eventClass: OSType(Int32(kEventClassKeyboard)),
        eventKind: UInt32(Int32(kEventHotKeyPressed))
    )

    static let signature: OSType = { OSType("Clip".fourCharCodeValue) }()

    static let eventHandlerCallback: EventHandlerUPP = { _, eventRef, _ in
        var receivedID = EventHotKeyID()
        let err = GetEventParameter(
            eventRef,
            EventParamName(kEventParamDirectObject),
            EventParamType(typeEventHotKeyID),
            nil,
            MemoryLayout<EventHotKeyID>.size,
            nil,
            &receivedID
        )
        if err == noErr {
            if receivedID.signature == HotkeyManager.signature && receivedID.id == 1 {
                HotkeyManager.shared.handler?()
            }
        } else {
            Log.hotkey.error("GetEventParameter failed: \(err)")
        }
        return noErr
    }

    /// Registers (or re-registers) the global hotkey. Safe to call multiple times.
    func registerHotkey(keyCode: UInt32, modifiers: UInt32, handler: @escaping () -> Void) {
        DispatchQueue.main.async {
            self.handler = handler

            if let ref = self.hotKeyRef {
                let status = UnregisterEventHotKey(ref)
                if status != noErr { Log.hotkey.error("Unregister existing hotkey failed: \(status)") }
                self.hotKeyRef = nil
            }

            if self.eventHandlerRef == nil {
                var ref: EventHandlerRef?
                let installStatus = InstallEventHandler(
                    GetApplicationEventTarget(),
                    HotkeyManager.eventHandlerCallback,
                    1,
                    [HotkeyManager.eventSpec],
                    nil,
                    &ref
                )
                if installStatus != noErr {
                    Log.hotkey.error("InstallEventHandler failed: \(installStatus)")
                } else {
                    self.eventHandlerRef = ref
                }
            }

            let hotKeyID = EventHotKeyID(signature: HotkeyManager.signature, id: UInt32(1))
            let status = RegisterEventHotKey(
                keyCode,
                modifiers,
                hotKeyID,
                GetApplicationEventTarget(),
                0,
                &self.hotKeyRef
            )

            if status == noErr {
                Log.hotkey.info("Hotkey registered (keyCode=\(keyCode), mods=\(modifiers))")
            } else {
                Log.hotkey.error("RegisterEventHotKey failed: \(status)")
            }
        }
    }

    func unregisterHotkey() {
        if let ref = hotKeyRef {
            let status = UnregisterEventHotKey(ref)
            if status != noErr { Log.hotkey.error("Unregister hotkey failed: \(status)") }
            hotKeyRef = nil
        }
        if let handlerRef = eventHandlerRef {
            RemoveEventHandler(handlerRef)
            eventHandlerRef = nil
        }
        handler = nil
    }
}

// MARK: - Auto Paster

/// Tracks the most-recently active non-self application and pastes into it
/// by synthesizing a Cmd-V keystroke after activating that app.
///
/// Requires Accessibility permission; prompts on first paste attempt. If the
/// user denies, the clipboard still contains the text and they can paste manually.
final class AutoPaster {
    static let shared = AutoPaster()
    private init() {}

    static var lastActiveApp: NSRunningApplication?
    private static var didPromptForAX = false

    static func startTracking() {
        let nc = NSWorkspace.shared.notificationCenter
        nc.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil,
            queue: .main
        ) { note in
            guard let app = note.userInfo?[NSWorkspace.applicationUserInfoKey] as? NSRunningApplication else { return }
            if app.bundleIdentifier != Bundle.main.bundleIdentifier {
                lastActiveApp = app
            }
        }
        // Seed with whatever's currently frontmost (the user, before us).
        if let front = NSWorkspace.shared.frontmostApplication,
           front.bundleIdentifier != Bundle.main.bundleIdentifier {
            lastActiveApp = front
        }
    }

    /// Snapshots the current frontmost app as the paste target. Call this *before*
    /// activating our own app (e.g., before showing the floating panel).
    static func captureFrontmost() {
        if let app = NSWorkspace.shared.frontmostApplication,
           app.bundleIdentifier != Bundle.main.bundleIdentifier {
            lastActiveApp = app
            Log.autopaste.info("Captured target app: \(app.localizedName ?? "?", privacy: .public)")
        }
    }

    /// Copies `text` to the clipboard and synthesizes Cmd-V into the previously active app.
    /// Polls for the target app to actually become frontmost before posting the keystroke
    /// so the paste lands in the right place regardless of activation timing.
    static func pasteIntoPreviousApp(text: String) {
        NSPasteboard.general.copyString(text)

        guard let app = lastActiveApp else {
            Log.autopaste.info("No previous app captured; text on clipboard only.")
            return
        }

        guard ensureAccessibilityTrust() else {
            Log.autopaste.info("Accessibility not trusted; text on clipboard only.")
            return
        }

        Log.autopaste.info("Activating target: \(app.localizedName ?? "?", privacy: .public) (pid=\(app.processIdentifier))")
        app.activate(options: [])

        // Wait for the target app to actually be frontmost before injecting the keystroke.
        // 500ms total budget, polled every 20ms.
        let deadline = Date().addingTimeInterval(0.5)
        waitUntilFrontmost(app: app, deadline: deadline)
    }

    private static func waitUntilFrontmost(app: NSRunningApplication, deadline: Date) {
        if NSWorkspace.shared.frontmostApplication?.processIdentifier == app.processIdentifier {
            sendCmdV()
            return
        }
        if Date() >= deadline {
            Log.autopaste.error("Target app did not become frontmost in time; clipboard only.")
            return
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.02) {
            waitUntilFrontmost(app: app, deadline: deadline)
        }
    }

    private static func ensureAccessibilityTrust() -> Bool {
        if AXIsProcessTrusted() { return true }
        if !didPromptForAX {
            didPromptForAX = true
            let opts: NSDictionary = ["AXTrustedCheckOptionPrompt": true]
            _ = AXIsProcessTrustedWithOptions(opts)
        }
        return false
    }

    private static func sendCmdV() {
        let v = CGKeyCode(kVK_ANSI_V)
        let down = CGEvent(keyboardEventSource: nil, virtualKey: v, keyDown: true)
        let up   = CGEvent(keyboardEventSource: nil, virtualKey: v, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
        Log.autopaste.info("Posted Cmd-V")
    }
}

// MARK: - Utilities

extension String {
    /// Packs up to four ASCII code points into a 32-bit `FourCharCode`. Asserts that
    /// the input fits — silent truncation would produce a misleading signature.
    var fourCharCodeValue: FourCharCode {
        precondition(unicodeScalars.count <= 4, "fourCharCodeValue requires a string of at most 4 scalars; got \(unicodeScalars.count)")
        var result: FourCharCode = 0
        for scalar in unicodeScalars {
            result = (result << 8) + FourCharCode(scalar.value & 0xFF)
        }
        return result
    }
}

extension NSPasteboard {
    func copyString(_ string: String) {
        clearContents()
        setString(string, forType: .string)
    }
}
